[lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
too_many_arguments = "deny"
manual_map = "warn"
redundant_else = "warn"
map_err_ignore = "deny"

# More from skills
clone_on_copy = "warn"

[lints.rust]
unsafe_code = "deny"